name: Publish npm Package

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.12.0

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Create this secret in your GitHub repository settings
